name: Github Pages

on:
  push:
    branches:
      - master
    path:
      - '**'
    
      
jobs:
  docs:
    runs-on: ubuntu-latest # 指定运行所需要的虚拟机环境（必填）
    if: ${{ github.event_name == 'push' && contains(github.event.head_commit.message, '[build]')}}

    steps:
      - name: Checkout
        if: ${{ contains(github.event.head_commit.message, '[build]') }}
        uses: actions/checkout@master
      
      - name: vuepress-deploy
        if: ${{ contains(github.event.head_commit.message, '[build]') }}
        uses: jenkey2011/vuepress-deploy@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: fncheng/blog
          TARGET_BRANCH: gh-pages
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vuepress/dist
          # CNAME: https://www.xxx.com
